#############################################

# Pricing European Plain-Vanilla options via Levy Processes

# created by Joseph Loss
# Copyright 2019

#############################################
library(BH)
library(BSDA)
library(crayon)
library(DistributionUtils)
library(dplyr)
library(Ecfun)
library(fBasics)
library(fda)
library(flexsurv)
library(jrvFinance)
library(fAssets)
library(FNN)
library(Formula)
library(FinancialMath)
library(GeneralizedHyperbolic)
library(GGally)
library(highr)
library(Hmisc)
library(hms)
library(latticeExtra)
library(lintr)
library(MASS)
library(mclust)
library(moments)
library(muhaz)
library(mvtnorm)
library(numDeriv)
library(pillar)
library(plotly)
library(PortfolioAnalytics)
library(prettyunits)
library(progress)
library(quantmod)
library(Rcpp)
library(RcppArmadillo)
library(readr)
library(sde)
library(stabledist)
library(stats)
library(stats4)
library(styler)
library(survival)
library(tbl2xts)
library(tibble)
library(tidyr)
library(fGarch)
library(boot)
library(e1071)
library(bootstrap)
library(urca)
library(quadprog)
library(tseries)
library(xts)
library(Metrics)
library(AER)
library(caret)
library(fExoticOptions)
library(fOptions)
library(TTR)
library(kernlab)
library(qrmtools)
library(quantreg)
library(derivmkts)
library(fOptions)
library(QRM)
library(ragtop)



options<-getOptionChain("^DJX")
options



